name: gradiend-de
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=3_gnu
  - absl-py=2.1.0=py39h06a4308_0
  - accelerate=1.0.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.4.3=py39h06a4308_0
  - aiohttp=3.10.9=py39h9399b63_1
  - aiosignal=1.3.1=pyhd8ed1ab_1
  - alembic=1.13.3=py39h06a4308_0
  - alsa-lib=1.2.12=h4ab18f5_0
  - annotated-types=0.6.0=py39h06a4308_1
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - anyio=4.6.0=pyhd8ed1ab_1
  - aom=3.6.1=h59595ed_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py39h5eee18b_1
  - arrow=1.3.0=py39h06a4308_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=py39h06a4308_0
  - async-timeout=4.0.3=py39h06a4308_0
  - attrs=24.2.0=py39h06a4308_0
  - aws-c-auth=0.7.31=h57bd9a3_0
  - aws-c-cal=0.7.4=hfd43aa1_1
  - aws-c-common=0.9.28=hb9d3cd8_0
  - aws-c-compression=0.2.19=h756ea98_1
  - aws-c-event-stream=0.4.3=h29ce20c_2
  - aws-c-http=0.8.10=h5e77a74_0
  - aws-c-io=0.14.18=h4e6ae90_11
  - aws-c-mqtt=0.10.7=h02abb05_0
  - aws-c-s3=0.6.6=h834ce55_0
  - aws-c-sdkutils=0.1.19=h756ea98_3
  - aws-checksums=0.1.20=h756ea98_0
  - aws-crt-cpp=0.28.3=h3e6eb3e_6
  - aws-sdk-cpp=1.11.407=h9f1560d_0
  - azure-core-cpp=1.13.0=h935415a_0
  - azure-identity-cpp=1.9.0=hd126650_0
  - azure-storage-blobs-cpp=12.13.0=h1d30c4a_0
  - azure-storage-common-cpp=12.8.0=ha3822c6_0
  - azure-storage-files-datalake-cpp=12.12.0=h0f25b8a_0
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=py39h06a4308_0
  - black=25.1.0=py39h06a4308_0
  - blas=1.0=openblas
  - bleach=6.1.0=pyhd8ed1ab_0
  - bottleneck=1.4.2=py39ha9d4c09_0
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - brotli-python=1.1.0=py39hf88036b_3
  - brotlicffi=1.0.9.2=py39hbdd6827_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.1=heb4867d_0
  - ca-certificates=2025.7.15=h06a4308_0
  - cached-property=1.5.2=py_0
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=hebfffa5_3
  - catalogue=2.0.10=py39h06a4308_0
  - certifi=2025.8.3=py39h06a4308_0
  - cffi=1.17.1=py39h1fdaa30_1
  - charset-normalizer=3.4.0=pyhd8ed1ab_1
  - click=8.1.7=py39h06a4308_0
  - cloudpathlib=0.16.0=py39h06a4308_1
  - colorama=0.4.6=py39h06a4308_0
  - colorlog=6.8.2=py39hf3d152e_1
  - comm=0.2.2=pyhd8ed1ab_1
  - confection=0.1.4=py39h2f386ee_0
  - contourpy=1.3.0=py39h74842e3_2
  - cpython=3.9.23=py39hd8ed1ab_0
  - cuda-cudart=12.4.99=hd3aeb46_0
  - cuda-cudart_linux-64=12.4.99=h59595ed_0
  - cuda-cupti=12.4.127=h6a678d5_1
  - cuda-libraries=12.4.0=ha770c72_0
  - cuda-nvrtc=12.4.99=hd3aeb46_0
  - cuda-nvtx=12.4.127=h6a678d5_1
  - cuda-opencl=12.4.99=h59595ed_0
  - cuda-runtime=12.4.0=ha804496_0
  - cuda-version=12.4=hbda6634_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - cymem=2.0.6=py39h6a678d5_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - datasets=3.0.1=pyhd8ed1ab_0
  - dbus=1.13.6=hb2f20db_0
  - debugpy=1.8.6=py39hf88036b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.3.8=py39h06a4308_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - double-conversion=3.3.0=h59595ed_0
  - entrypoints=0.4=py39h06a4308_0
  - eval_type_backport=0.2.2=pyha770c72_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.6.3=h6a678d5_0
  - ffmpeg=4.4.2=gpl_hdf48244_113
  - filelock=3.16.1=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.54.1=py39h9399b63_1
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.4.1=py39h8cd3c5a_1
  - fsspec=2024.6.1=py39h06a4308_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.2=h5eee18b_0
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.43=py39h06a4308_0
  - glib=2.82.1=h44428e9_1
  - glib-tools=2.82.1=h4833e2c_1
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.1.5=py39h7196dd7_3
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.13=h23475e2_0
  - greenlet=3.1.1=py39h6a678d5_0
  - grpcio=1.65.5=py39hf8b6b1a_0
  - h11=0.14.0=py39h06a4308_0
  - h2=4.1.0=pyhd8ed1ab_1
  - harfbuzz=9.0.0=hda332d3_1
  - hpack=4.0.0=py_0
  - httpcore=1.0.6=pyhd8ed1ab_0
  - httpx=0.27.2=pyhd8ed1ab_0
  - humanize=4.12.2=py39h06a4308_0
  - hydra-core=1.3.2=pyhd8ed1ab_1
  - hyperframe=6.0.1=pyhd3eb1b0_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.5.0=py39h06a4308_0
  - importlib-resources=6.4.5=pyhd8ed1ab_1
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - importlib_resources=6.4.5=pyhd8ed1ab_1
  - inflect=7.4.0=pyhd8ed1ab_1
  - intel-openmp=2022.0.1=h06a4308_3633
  - ipykernel=6.29.5=py39h06a4308_1
  - ipython=8.18.1=pyh707e725_3
  - ipywidgets=8.1.5=py39h06a4308_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.1=py39h06a4308_0
  - jinja2=3.1.4=py39h06a4308_1
  - joblib=1.4.2=py39h06a4308_0
  - json5=0.9.25=py39h06a4308_0
  - jsonpointer=3.0.0=py39h06a4308_0
  - jsonschema=4.23.0=py39h06a4308_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.2.5=py39h06a4308_0
  - jupyter_client=8.6.3=py39h06a4308_0
  - jupyter_console=6.6.3=py39h06a4308_0
  - jupyter_core=5.7.2=py39h06a4308_0
  - jupyter_events=0.10.0=py39h06a4308_0
  - jupyter_server=2.14.2=pyhd8ed1ab_1
  - jupyter_server_terminals=0.5.3=py39h06a4308_0
  - jupyterlab=4.2.5=py39h06a4308_0
  - jupyterlab_pygments=0.3.0=py39h06a4308_0
  - jupyterlab_server=2.27.3=py39h06a4308_0
  - jupyterlab_widgets=3.0.13=py39h06a4308_0
  - kaldi=5.5.1112=cpu_h7360626_9
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h7b6447c_0
  - langcodes=3.3.0=pyhd3eb1b0_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h1423503_5
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libarrow=17.0.0=h364f349_20_cpu
  - libarrow-acero=17.0.0=h5888daf_20_cpu
  - libarrow-dataset=17.0.0=h5888daf_20_cpu
  - libarrow-substrait=17.0.0=he882d9a_20_cpu
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libblas=3.9.0=26_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcblas=3.9.0=26_linux64_openblas
  - libclang-cpp19.1=19.1.1=default_hb5137d0_0
  - libclang13=19.1.1=default_h9c6a7e4_0
  - libcrc32c=1.1.2=h6a678d5_0
  - libcublas=12.4.2.65=hd3aeb46_0
  - libcufft=11.2.0.44=hd3aeb46_0
  - libcufile=1.9.0.20=hd3aeb46_0
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.5.119=hd3aeb46_0
  - libcurl=8.10.1=hbbe4b11_0
  - libcusolver=11.6.0.99=hd3aeb46_0
  - libcusparse=12.3.0.142=hd3aeb46_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.123=hb9d3cd8_0
  - libedit=3.1.20191231=h14c3975_1
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h6a678d5_6
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.82.1=h2ff4ddf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.1.0=h77fa898_1
  - libgoogle-cloud=2.29.0=h438788a_1
  - libgoogle-cloud-storage=2.29.0=h0121fbd_1
  - libgrpc=1.65.5=hf5c653b_0
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=26_linux64_openblas
  - liblapacke=3.9.0=26_linux64_openblas
  - libllvm19=19.1.1=ha7bfdaf_0
  - libnghttp2=1.58.0=h47da74e_1
  - libnpp=12.2.5.2=hd3aeb46_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.4=h14c3975_2
  - libnvfatbin=12.4.99=hd3aeb46_0
  - libnvjitlink=12.4.99=hd3aeb46_0
  - libnvjpeg=12.3.1.89=h59595ed_0
  - libopenblas=0.3.28=pthreads_h94d23a6_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libparquet=17.0.0=h6bd9018_20_cpu
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.44=hadc24fc_0
  - libpq=17.0=h04577a9_4
  - libprotobuf=5.27.5=h5b01275_2
  - libre2-11=2023.11.01=hbbce691_0
  - libsodium=1.0.20=heac8642_0
  - libsqlite=3.46.1=hadc24fc_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.21.0=h0e7cc3e_0
  - libtiff=4.7.0=he137b08_1
  - libtorch=2.4.1=cpu_generic_hca457ed_2
  - libunistring=0.9.10=h27cfd23_0
  - libutf8proc=2.8.0=hf23e847_1
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.51.0=hb03c661_1
  - libva=2.22.0=h8a09558_1
  - libvpx=1.13.1=h6a678d5_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.12.7=he7c6b58_4
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb25bd0a_0
  - lightning-utilities=0.11.9=py39h06a4308_0
  - llvm-openmp=15.0.7=h0cdce71_0
  - lz4-c=1.9.4=h6a678d5_1
  - mako=1.3.5=pyhd8ed1ab_0
  - markdown=3.6=pyhd8ed1ab_0
  - markdown-it-py=2.2.0=py39h06a4308_1
  - markupsafe=3.0.1=py39h9399b63_1
  - matplotlib=3.9.2=py39hf3d152e_2
  - matplotlib-base=3.9.2=py39hbfdbfaf_1
  - matplotlib-inline=0.1.7=py39h06a4308_0
  - mdurl=0.1.0=py39h06a4308_0
  - mistune=3.0.2=pyhd8ed1ab_1
  - mkl=2022.1.0=hc2b9512_224
  - more-itertools=10.5.0=pyhd8ed1ab_1
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py39h06a4308_0
  - multidict=6.1.0=py39h5eee18b_0
  - multiprocess=0.70.16=py39h8cd3c5a_1
  - munkres=1.1.4=py_0
  - murmurhash=1.0.12=py39h6a678d5_0
  - mypy_extensions=1.0.0=py39h06a4308_0
  - mysql-common=9.0.1=h266115a_4
  - mysql-libs=9.0.1=he0572af_4
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=py39h06a4308_1
  - nbformat=5.10.4=py39h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py39h06a4308_0
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.2.1=py39h06a4308_0
  - nomkl=3.0=0
  - notebook=7.2.2=py39h06a4308_1
  - notebook-shim=0.2.4=py39h06a4308_0
  - numexpr=2.10.1=py39hd28fd6d_0
  - ocl-icd=2.3.2=h5eee18b_1
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openfst=1.8.3=h84d6215_3
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.8=hedd0468_0
  - openssl=3.4.0=h7b32b05_1
  - optuna=4.0.0=pyhd8ed1ab_0
  - orc=2.0.2=h690cf93_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=24.1=py39h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=py39h06a4308_0
  - pathspec=0.12.1=py39h06a4308_1
  - patsy=0.5.6=py39h06a4308_0
  - pcre2=10.44=hc749103_2
  - pexpect=4.9.0=py39h06a4308_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.4.0=py39h648eaa6_1
  - pip=24.2=py39h06a4308_0
  - pixman=0.43.2=h59595ed_0
  - pkgutil-resolve-name=1.3.10=py39h06a4308_1
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - plotly=5.24.1=py39h2f386ee_1
  - preshed=3.0.8=py39h6a678d5_0
  - prometheus_client=0.21.0=py39h06a4308_0
  - prompt-toolkit=3.0.48=pyha770c72_1
  - prompt_toolkit=3.0.48=hd8ed1ab_1
  - protobuf=5.27.5=py39hf88036b_0
  - psutil=6.0.0=py39h8cd3c5a_2
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py39h06a4308_0
  - pyarrow=17.0.0=py39he8689d4_2
  - pyarrow-core=17.0.0=py39h6117c73_2_cpu
  - pybind11-abi=4=hd3eb1b0_1
  - pycparser=2.22=py39h06a4308_0
  - pydantic-core=2.27.1=py39h4aa5aa6_0
  - pygments=2.18.0=pyhd8ed1ab_1
  - pynvml=11.5.3=pyhd8ed1ab_1
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyside6=6.7.3=py39h0383914_1
  - pysocks=1.7.1=py39h06a4308_1
  - python=3.9.19=h0755675_0_cpython
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python-fastjsonschema=2.20.0=py39h06a4308_0
  - python-json-logger=2.0.7=py39h06a4308_0
  - python-tzdata=2024.2=pyhd8ed1ab_1
  - python-xxhash=3.5.0=py39h8cd3c5a_1
  - python_abi=3.9=8_cp39
  - pytorch-cuda=12.4=hc786d27_6
  - pytorch-lightning=2.4.0=pyh101cb37_1
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py39h06a4308_0
  - pyyaml=6.0.2=py39h5eee18b_0
  - pyzmq=26.2.0=py39h6a678d5_0
  - qhull=2020.2=hdb19cb5_2
  - qt6-main=6.7.3=h6e8976b_1
  - re2=2023.11.01=h77b4e00_0
  - readline=8.2=h5eee18b_0
  - referencing=0.35.1=pyhd8ed1ab_1
  - regex=2024.9.11=py39h5eee18b_0
  - requests=2.32.3=py39h06a4308_1
  - rfc3339-validator=0.1.4=py39h06a4308_0
  - rfc3986-validator=0.1.1=py39h06a4308_0
  - rich=13.9.4=py39h06a4308_0
  - rpds-py=0.20.0=py39he612d8f_1
  - s2n=1.5.4=h1380c3d_0
  - safetensors=0.4.5=py39h922eef2_1
  - scikit-learn=1.5.2=py39h6a678d5_0
  - scipy=1.13.1=py39heeff2f4_1
  - seaborn=0.13.2=py39h06a4308_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh0d859eb_1
  - sentry-sdk=2.18.0=py39h06a4308_0
  - setproctitle=1.2.2=py39h27cfd23_1004
  - setuptools=75.1.0=py39h06a4308_0
  - shellingham=1.5.0=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sleef=3.9.0=ha0421bc_0
  - smart_open=5.2.1=py39h06a4308_0
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.5=py39h06a4308_0
  - spacy-legacy=3.0.12=py39h06a4308_0
  - spacy-loggers=1.0.4=py39h06a4308_0
  - sqlalchemy=2.0.35=py39h8cd3c5a_0
  - srsly=2.5.1=py39h6a678d5_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.4=py39h5eee18b_0
  - svt-av1=1.4.1=hcb278e6_0
  - tabulate=0.9.0=py39h06a4308_0
  - tensorboard=2.18.0=py39h06a4308_0
  - tensorboard-data-server=0.7.0=py39h52d8a92_1
  - terminado=0.18.1=py39h06a4308_0
  - threadpoolctl=3.5.0=py39h2f386ee_0
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - tomli=2.0.2=pyhd8ed1ab_0
  - torchmetrics=1.5.2=pyhd8ed1ab_1
  - tornado=6.4.1=py39h5eee18b_0
  - tqdm=4.66.5=py39h2f386ee_0
  - traitlets=5.14.3=py39h06a4308_0
  - typeguard=4.3.0=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20241003=pyhd8ed1ab_1
  - typing=3.10.0.0=py39h06a4308_0
  - typing-extensions=4.12.2=py39h06a4308_0
  - typing_extensions=4.12.2=py39h06a4308_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py39h5eee18b_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - wandb=0.21.0=py39h43652db_0
  - wasabi=0.9.1=py39h06a4308_0
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.37=hd8ed1ab_0
  - wcwidth=0.2.13=py39h06a4308_0
  - weasel=0.3.4=py39h06a4308_0
  - webcolors=24.8.0=pyhd8ed1ab_1
  - webencodings=0.5.1=py39h06a4308_1
  - websocket-client=1.8.0=py39h06a4308_0
  - werkzeug=3.0.4=pyhd8ed1ab_0
  - wheel=0.44.0=py39h06a4308_0
  - widgetsnbextension=4.0.13=py39h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-libice=1.1.1=hb9d3cd8_1
  - xorg-libsm=1.2.4=he73a12e_1
  - xorg-libx11=1.8.10=h4f16b4b_1
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.2=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.11=hb9d3cd8_2
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.5=hb9d3cd8_4
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xxhash=0.8.2=hd590300_0
  - xz=5.2.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.13.1=py39h8cd3c5a_0
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.20.2=py39h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
  - zstandard=0.23.0=py39h2c38b39_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - blis==0.7.11
      - compound-split==1.0.2
      - de-core-news-sm==3.5.0
      - derbi==1.2
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - matplotlib-venn==1.1.2
      - minicons==0.3.31
      - nltk==3.7
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - pandas==2.2.0
      - pathlib-abc==0.1.1
      - pathy==0.11.0
      - pydantic==1.10.22
      - pympler==1.1
      - pyupset==0.1.1.post7
      - sentencepiece==0.2.0
      - spacy==3.5.1
      - sympy==1.13.1
      - tenacity==8.5.0
      - thinc==8.1.12
      - tokenizers==0.22.1
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - transformers==4.57.1
      - triton==3.1.0
      - typer==0.7.0
      - upsetplot==0.9.0
      - upsetty==0.1.3
      - urllib3==1.26.20
      - venn==0.1.3
      - wonderwords==2.2.0
prefix: /root/envs/gradiend-de
