defaults:
  - mode: gradiend_encoder
  - pairing: MN
  - _self_

augment_neutral: True
eval_only: False
base_model: 'bert-base-german-cased'
num_runs: 3
hydra:
  run: 
    dir: logs/experiments/${mode.name}/${pairing.plot_name}/dim_${mode.model_config.num_dims}_${mode.model_config.source}/${basename:${base_model}}/
  output_subdir: null
